### ISSUE TITLE
模型测试

### ISSUE THREAD

**Issue by Xuziqi-come** [TD-GC/TD-GCN-Gesture#1]
您好！请问怎样将训练后的模型测试呢？我在项目里没有找到相关代码

**Comment by liujf69** [comment]
Thanks for your question! 
You can use `python main.py --config <config_path> --work-dir <workdir_path> --phase test --save-score True --weights <weight_path> --device <device>` to test.
A example to test on SHREC’17 Track dataset:
`python main.py --config ./config/shrec17/shrec17.yaml --work-dir ./work_dir/shrec17/14joint_1108 --phase test --save-score True --weights ./checkpoints/Shrec17/14label_joint.pt --device 0`

**Comment by liujf69** [comment]
> 您好！请问怎样将训练后的模型测试呢？我在项目里没有找到相关代码

Thanks for your question!
You can use `python main.py --config <config_path> --work-dir <workdir_path> --phase test --save-score True --weights <weight_path> --device <device>` to test the model.
A example to test on SHREC’17 Track dataset:
`python main.py --config ./config/shrec17/shrec17.yaml --work-dir ./work_dir/shrec17/14joint_1108 --phase test --save-score True --weights ./checkpoints/Shrec17/14label_joint.pt --device 0`
