### ISSUE TITLE
There is no “DictAction ” in the torchlight folder in main.py.

### ISSUE THREAD

**Issue by QienJane** [TD-GC/TD-GCN-Gesture#12]
hello，
 I find there is no “DictAction ” in the torchlight folder in main.py. 
 Can you provide “DictAction ”？
![image](https://github.com/user-attachments/assets/261de5fe-1835-4172-a4f6-798a07cc1530)

**Comment by liujf69** [comment]
Thanks for your question!
You only need to follow the instructions below to install the torchlight library.
```
cd TD-GCN-Gesture
pip install -e torchlight
```
Then, the main program does not depend on the provided torchlight source code.
I hope my answer can help you!
