### ISSUE TITLE
Hello, how did the "NTU60_XSub_Val.txt" get it, I would like to use your txt way ensemble on the ntu120 dataset as well.

### ISSUE THREAD

**Issue by z-boboxin** [TD-GC/TD-GCN-Gesture#13]

**Comment by liujf69** [comment]
Thanks for your question!
Please review our other work:
[EPP-Net-Action](https://github.com/liujf69/EPP-Net-Action/tree/master/Ensemble/Val_Sample)
I hope my answer can help you!

**Comment by z-boboxin** [comment]
That's OK. Thank you very much!
