### ISSUE TITLE
Reproducing the result reported in the paper in Table XI 

### ISSUE THREAD

**Issue by Gbouna** [TD-GC/TD-GCN-Gesture#4]
Thanks for the awesome work; very helpful. We have reproduced your work using the default settings and got very similar accuracy as reported in Table XI for TD-GCN (joint only). There is however no instruction in your repository on how to train your model to get the result for TD-GCN which is 97.4. What configuration is required to get that result? @liujf69

**Comment by liujf69** [comment]
Thanks for your question!
We have uploaded the corresponding code to the ensemble folder.
I have also explained more details in the previous email you sent.
