### ISSUE TITLE
shrec17复现问题

### ISSUE THREAD

**Issue by tym7777** [TD-GC/TD-GCN-Gesture#5]
您好，有两个问题想请教一下：
①.我最近正在复现您的文章在shrec17数据集上的结果，使用您checkpoint中提供的模型权重文件可以达到论文中的结果，但是当我重新使 用您的默认配置文件config/shrec17/shrec17.yaml 自己训练时却无法复现您的结果Table VIII（28gesture, J Only 93.57%）
我实验时得到的结果是 ：（单卡跑 28gesture, J Only 91.79）（双卡跑 28gesture, J Only 92.38），请问能否提供你的训练结果中更加具体的复现环境/代码/配置？
②. 看到您的gesture_ensemble.py 中line77的Rate是初始化为Rate = [0., 0., 0.]  ，我对于这一行不太理解，因为0是得不到结果的，想问一下这个值应该怎样设置？
非常期待您的回复，谢谢！

**Comment by liujf69** [comment]
Thanks for your question. 

For the first question, maybe you can use one GPU for training and set the hyperparameters self.beta and self.gamma to 2.0 and 0.1 respectively.

For the second question, we have uploaded the corresponding score pkl file to Google Drive, and you can download [them](https://drive.google.com/drive/folders/1ux87mUirBQjmA4b4fEWtb9tuj-8wSYHt?usp=sharing) for testing. The ratio of joint, bone and jointmotion can be set to 0.5:0.5:0.5 or 0.5:0.3:0.2.

I hope my answer can help you.
