### ISSUE TITLE
DHG-14/28数据集的链接失效了，请问能否提供这个数据集呢？

### ISSUE THREAD

**Issue by yunfan258** [TD-GC/TD-GCN-Gesture#6]
DHG-14/28 dataset from http://www-rech.telecom-lille.fr/DHGdataset/

这个链接打不开，显示网页无法正常工作，请问能否提供云盘的下载链接呢？或者其他有效的链接

**Comment by yunfan258** [comment]
又能打开了

**Comment by 146152** [comment]
您好，请问您还有这个数据集吗，可以给我发一份吗
